### ISSUE TITLE
Unable to recover from misinput to read_i64

### ISSUE THREAD

**Issue by Costava** [maximecb/uvm#26]
The `read_i64` syscall has no way to recover from invalid input.  
The program crashes.  
This would likely be frustrating to users of long-running programs where mistyping "4r" instead of "4" will bring the whole program down.

Recovery would mean some action like using a default value instead and/or being able to retry.

The syscalls doc states that each syscall outputs either no value or a single value onto the stack.

In the event of invalid input:

1. `read_i64` could not push onto the stack, but returning is fixed as void or not void, and if it wasn't, there would still need to be a way to check if the stack has grown or not, otherwise would be checking against a sentinel value put onto the stack.

2. `read_i64` could return some sentinel value in the event of invalid input.

3. `read_i64` could take a single argument, a "default" value, that is returned in the event of invalid input.

It would be nice if sentinel values can be avoided, and if invalid input could be known without having to assume that the user has not entered the default value.

Option 1 is not possible with the current constraints (not that the constraints should be changed), and 2 and 3 have shortcomings. I'm sure someone can determine a better setup.

**Comment by maximecb** [comment]
Hi @Costava 

You're right that this is a bit of a conundrum.

The reason I stated in the doc that syscalls should return either 0 or 1 value is that it might be hard to support a variable number of return values in a language like C. If we allow returning multiple values, we can't directly map syscalls to C functions. Which is maybe something we can live with.

There's also an option 4, which would be to get rid of `read_i64` and let programs do their own parsing based on a lower level syscall that's more like [`getchar`](https://www.tutorialspoint.com/c_standard_library/c_function_getchar.htm).

**Comment by maximecb** [comment]
Alright. Sorry this took a while, had a stressful move, but I am back, and I implemented a fix in https://github.com/maximecb/uvm/commit/56a5814b49924518d60c3da1e0ce2103f53da4c6

I added a `getchar()` syscall and removed `read_i64()`.

If that's too inconvenient, we could also consider adding a `read_i32()` instead, which could then use `INT64_MAX` as a sentinel value.
