### ISSUE TITLE
Should the VM provide FP functions such as sin, cos, tan, log, etc?

### ISSUE THREAD

**Issue by maximecb** [maximecb/uvm#4]
There's an open question in my mind as to whether UVM should provide the "standard" set of floating-point functions and other functions found in C's [`math.h`](https://cplusplus.com/reference/cmath/) as part of the VM itself.

The `sin` and `cos` functions are very often used in graphics for example. The argument in favor of this would be that it makes UVM an easier platform to target. The argument against would be that it's possible to implement all of those functions using Taylor series expansions, and CPU-specific cosine instructions on intel CPUs for example aren't particularly fast.

An argument for implementing functions like sin/cos in userspace would be that they run the same on every platform. That being said, this argument might be moot because AFAIK, basic floating-point operations such as add/sub/mul don't produce the same result on every platform due to hardware differences. For instance, Intel hardware can use 80 bits of precision internally whereas other platforms use 64 bits. It's also the case that it's easier for the host system to accelerate an operation like sin/cos with SIMD instructions than it is for code written inside UVM.

At the moment I'm leaning towards the host should probably provide at least a set of core FP math functions such as sin, cos, sqrt, but open to discussing this. It's always possible to add more of these functions later. The functions would probably be added as syscalls under a `math` subsystem rather than core instructions.

**Comment by maximecb** [comment]
After thinking about this some more, I'm leaning on the side of having a few of these functions directly included as opcodes. Part of the reason is that it would help these ops perform better on the interpreter. I want to have a JIT compiler eventually, but that doesn't mean we can't take some steps to have the interpreter perform as well as possible.

**Comment by Robert-M-Muench** [comment]
Portable FP is a pandora's box. If you implement it all in the VM, it will be too slow for any FP-intensive code anyway. Providing the opcodes and JITting to the host later looks more practical.

The FP behavior is the duty of the program developer anyway because even different compilers on the same platform generate different FP code leading to different results.

**Comment by maximecb** [comment]
Once we reach the point where UVM is ready for a JIT compiler to be implemented, I'm confident that we can have good FP performance. That being said, I'd still like to have the FP instructions in the instruction set now, because I don't really want to force people to use fixed point math for everything. I think that this would probably make UVM challenging for newcomers to target if people have to figure out how to make games using fixed point math and implement their own approximation for functions like cosine, etc.
